routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserAdminController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::prefix('admin')->middleware(['auth', 'auth.status'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserAdminController::class);
    Route::put('/user/{id}/password', [UserAdminController::class, 'updatePassword'])->name('user.update.password');

    Route::resource('role', RoleController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('setting', SettingController::class);

    Route::resource('category', CategoryController::class);
    Route::resource('product', ProductController::class);

    Route::resource('transaction', TransactionController::class);

});

app/Http/Livewire/Admin/SetRolePermission.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Permission;

class SetRolePermission extends Component
{
    public $permission, $selected = [], $selectAll = false;

    public function mount()
    {
        $this->permission = Permission::select('id', 'name', 'group')->orderBy('name', 'asc')->get()->groupBy('group')->toArray();
    }

    public function render()
    {
        if (Permission::count() == count($this->selected)) {
            $this->selectAll = true;
        }

        return view('livewire.admin.set-role-permission');
    }

    public function updatedSelectAll($value) 
    {
        $permission = Permission::get();

        if ($value) {
            $this->selected = $permission->pluck('name');
        } else {
            $this->selected = [];
        }
    }

    public function updatedSelected()
    {
        if (Permission::count() == count($this->selected)) {
            $this->selectAll = true; 
        } else {
            $this->selectAll = false; 
        }
    }
}

app/Http/Livewire/Admin/ShowCategory.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Category as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowCategory extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";

    public $title, $model, $modelId;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->filter($this->search)
            ->paginate($this->paginate);

        return view('livewire.admin.show-category', [
            'table' => $table,
        ]);
    }

}

app/Http/Livewire/Admin/ShowMenu.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Menu as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowMenu extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";
    public $selected = [];
    public $selectAll = false;

    public $title, $model, $modelId;

    public function hydrate()
    {
        $this->emit('dragdrop');
    }

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->filter($this->search)
            ->orderBy('main_menu', 'asc')
            ->orderBy('sort', 'asc')
            ->paginate($this->paginate);

        return view('livewire.admin.show-menu', [
            'table' => $table,
        ]);
    }

    // Misc
    public function resetCreateForm()
    {   
        $data = ['modelId',];
        foreach ($data as $item) {
            $this->$item = "";
        }
    }

    public function closeModal()
    {
        $this->dispatchBrowserEvent('close-modal'); 
        $this->resetErrorBag(); 
        $this->resetCreateForm();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function modelId($id)
    {
        $this->modelId = $id;
    }

    public function updatedSelectAll($value) 
    {
        $model = $this->model
            ->filter($this->search)
            ->get();

        if ($value) {
            $this->selected = $model->pluck('id');
        } else {
            $this->selected = [];
        }
    }

    public function updateParentOrder($parent)
    {
        foreach ($parent as $key => $item) {
            $menu = $this->model->find($item['value']);
            $menu->update([
                'sort' => $item['order'],
            ]);
        }

        return $this->alert('success', alertMsg('update'), [
            'showCloseButton' => true,
        ]);
    }
    
    public function updateChildGroup($data)
    {
        foreach ($data as $key => $menu) {
            $parent_id = $menu['value'];
            $parent = $this->model::find($parent_id);
            $parent->update([
                'sort' => $menu['order'],
            ]);

            $child = $menu['items'];
            if ($child) {
                foreach ($child as $key => $child) {
                    $childMenu = $this->model->find($child['value']);
                    $childMenu->update([
                        'sort' => $child['order'],
                        'main_menu' => $parent_id,
                    ]);
                }
            }
        }

        return $this->alert('success', alertMsg('update'), [
            'showCloseButton' => true,
        ]);
    }
}

app/Http/Livewire/Admin/ShowPermission.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Permission as Model;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowPermission extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";
    public $selected = [];
    public $selectAll = false;

    public $title, $model, $modelId;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->filter($this->search)
            ->orderBy('group', 'asc')
            ->orderBy('id', 'asc')
            ->paginate($this->paginate);

        return view('livewire.admin.show-permission', [
            'table' => $table,
        ]);
    }

    // Misc
    public function resetCreateForm()
    {   
        $data = ['modelId',];
        foreach ($data as $item) {
            $this->$item = "";
        }
    }

    public function closeModal()
    {
        $this->dispatchBrowserEvent('close-modal'); 
        $this->resetErrorBag(); 
        $this->resetCreateForm();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function modelId($id)
    {
        $this->modelId = $id;
    }

    public function updatedSelectAll($value) 
    {
        $model = $this->model
            ->filter($this->search)
            ->get();

        if ($value) {
            $this->selected = $model->pluck('id');
        } else {
            $this->selected = [];
        }
    }
}

app/Http/Livewire/Admin/ShowProduct.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Product as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowProduct extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";

    public $title, $model;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->filter($this->search)
            ->paginate($this->paginate);

        return view('livewire.admin.show-product', [
            'table' => $table,
        ]);
    }

}

app/Http/Livewire/Admin/ShowRole.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Role as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowRole extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";
    public $selected = [];
    public $selectAll = false;

    public $title, $model, $modelId;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->whereNotIn('id', [1])
            ->filter($this->search)
            ->paginate($this->paginate);

        return view('livewire.admin.show-role', [
            'table' => $table,
        ]);
    }

    // Misc
    public function resetCreateForm()
    {   
        $data = ['modelId',];
        foreach ($data as $item) {
            $this->$item = "";
        }
    }

    public function closeModal()
    {
        $this->dispatchBrowserEvent('close-modal'); 
        $this->resetErrorBag(); 
        $this->resetCreateForm();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function modelId($id)
    {
        $this->modelId = $id;
    }

    public function updatedSelectAll($value) 
    {
        $model = $this->model
            ->whereNotIn('id', [1])
            ->filter($this->search)
            ->get();

        if ($value) {
            $this->selected = $model->pluck('id');
        } else {
            $this->selected = [];
        }
    }
}

app/Http/Livewire/Admin/ShowSetting.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Setting as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowSetting extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";
    public $selected = [];
    public $selectAll = false;

    public $title, $model, $modelId;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            // ->filter($this->search)
            ->take(1)
            ->paginate($this->paginate);

        return view('livewire.admin.show-setting', [
            'table' => $table,
        ]);
    }

    // Misc
    public function resetCreateForm()
    {   
        $data = ['modelId',];
        foreach ($data as $item) {
            $this->$item = "";
        }
    }

    public function closeModal()
    {
        $this->dispatchBrowserEvent('close-modal'); 
        $this->resetErrorBag(); 
        $this->resetCreateForm();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function modelId($id)
    {
        $this->modelId = $id;
    }

    public function updatedSelectAll($value) 
    {
        $model = $this->model
            // ->filter($this->search)
            ->get();

        if ($value) {
            $this->selected = $model->pluck('id');
        } else {
            $this->selected = [];
        }
    }
}

app/Http/Livewire/Admin/ShowTransaction.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\Transaction as Model;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowTransaction extends Component
{
    use LivewireAlert;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';

    public $paginate = 10;
    public $search = "";
    public $sortColumn = [
        'product' => '',
        'date' => '',
    ];

    public $title, $model, $modelId;

    public function mount(Model $model)
    {
        $this->model = $model;
    }

    public function sort($col)
    {
        if ($col) {
            if ($this->sortColumn[$col] === '') {
                $this->sortColumn[$col] = 'asc';
            } elseif ($this->sortColumn[$col] === 'asc') {
                $this->sortColumn[$col] = 'desc';
            } elseif ($this->sortColumn[$col] === 'desc') {
                $this->sortColumn[$col] = '';
            }
        }
    }

    public function render()
    {
        $table = $this->model
            ->join('products', 'transactions.product_id', '=', 'products.id')
            ->select('transactions.*')
            ->filter($this->search)
            ->when($this->sortColumn['product'], function ($query) {
                $query->orderBy('products.name', $this->sortColumn['product']);
            })
            ->when($this->sortColumn['date'], function ($query) {
                $query->orderBy('date', $this->sortColumn['date']);
            })
            ->when(empty($this->sortColumn['date']), function ($query) {
                $query->orderBy('date', 'asc');
            })
            ->paginate($this->paginate);

        return view('livewire.admin.show-transaction', [
            'table' => $table,
        ]);
    }

}

app/Http/Livewire/Admin/ShowUserAdmin.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
use Jantinnerezo\LivewireAlert\LivewireAlert;

class ShowUserAdmin extends Component
{
    use WithPagination, LivewireAlert;
    protected $paginationTheme = 'bootstrap';
    protected $paginationClasses = 'd-flex align-items-center';
    
    public $paginate = 10;
    public $search = "";
    public $selected = [];
    public $selectAll = false;

    public $title, $model, $modelId, $password = 'pin12345', $status = false;

    public function mount(User $model)
    {
        $this->model = $model;
    }

    public function render()
    {
        $table = $this->model
            ->administrator()
            ->filter($this->search)
            ->paginate($this->paginate);
        
        return view('livewire.admin.show-user-admin', [
            'table' => $table,
        ]);
    }

    // Misc
    public function resetCreateForm()
    {   
        $data = ['modelId', 'status'];
        foreach ($data as $item) {
            $this->$item = "";
        }
        $this->password = 'pin12345';
        $this->status = false;
    }

    public function closeModal()
    {
        $this->dispatchBrowserEvent('close-modal'); 
        $this->resetErrorBag(); 
        $this->resetCreateForm();
    }

    public function updated()
    {
        $this->resetPage();
    }

    public function modelId($id)
    {
        $this->modelId = $id;

        $model = $this->model->findOrFail($id);
        $this->status = $model->status;
    }

    public function updatedSelectAll($value)
    {
        $model = $this->model
            ->administrator()
            ->filter($this->search)
            ->get();

        if ($value) {
            $this->selected = $model->pluck('id');
        } else {
            $this->selected = [];
        }
    }

    // update
    public function updatePassword()
    {   
        $model = $this->model->find($this->modelId);
        $data = $this->validate([
            'password' => 'required|min:8',
        ]);

        $data['updated_by'] = auth()->user()->id;
        $model->update($data);

        $this->closeModal();
        return $this->alert('success', alertMsg('update'), [
            'showCloseButton' => true,
        ]);
        
    }

    public function updateStatus()
    {
        $model = $this->model->find($this->modelId);
        $data = $this->validate([
            'status' => ''
        ]);

        $data['updated_by'] = auth()->user()->id;
        $model->update($data);

        $this->closeModal();
        return $this->alert('success', alertMsg('update'), [
            'showCloseButton' => true,
        ]);
    }
    
    public function updateSelectedStatus()
    {
        $model = $this->model->whereKey($this->selected);
        $data = $this->validate([
            'status' => ''
        ]);

        $data['updated_by'] = auth()->user()->id;
        $model->update($data);

        $this->closeModal();
        $this->selected = [];
        $this->selectAll = false;
        return $this->alert('success', alertMsg('update'), [
            'showCloseButton' => true,
        ]);
    }


}

resources/views/livewire/admin/show-menu.blade.php
<div>
    <script>
        document.addEventListener('livewire:load', function () {
            $.fn.extend({
                treed: function (o) {
                
                var openedClass = 'fa-solid fa-folder-open fs-3';
                var closedClass = 'fa-solid fa-folder fs-3';
                
                if (typeof o != 'undefined'){
                    if (typeof o.openedClass != 'undefined'){
                    openedClass = o.openedClass;
                    }
                    if (typeof o.closedClass != 'undefined'){
                    closedClass = o.closedClass;
                    }
                };
                
                    //initialize each of the top levels
                    var tree = $(this);
                    tree.addClass("tree");
                    tree.find('li').has("ul").each(function () {
                        var branch = $(this); //li with children ul
                        branch.prepend("<i class='indicator glyphicon " + closedClass + "'></i>");
                        branch.addClass('branch');
                        branch.on('click', function (e) {
                            if (this == e.target) {
                                var icon = $(this).children('i:first');
                                icon.toggleClass(openedClass + " " + closedClass);
                                $(this).children().children().toggle();
                            }
                        })
                        branch.children().children().toggle();
                    });
                    
                    //fire event from the dynamically added icon
                    tree.find('.branch .indicator').each(function(){
                        $(this).on('click', function () {
                            $(this).closest('li').click();
                        });
                    });
                    //fire event to open branch if the li contains an anchor instead of text
                    tree.find('.branch>a').each(function () {
                        $(this).on('click', function (e) {
                            $(this).closest('li').click();
                            e.preventDefault();
                        });
                    });
                    //fire event to open branch if the li contains a button instead of text
                    tree.find('.branch>button').each(function () {
                        $(this).on('click', function (e) {
                            $(this).closest('li').click();
                            e.preventDefault();
                        });
                    });
                }
            });
        
            //Initialization of treeviews
            $('#tree1').treed();
            $('#tree2').treed({openedClass:'glyphicon-folder-open', closedClass:'glyphicon-folder-close'});
            $('#tree3').treed({openedClass:'glyphicon-chevron-right', closedClass:'glyphicon-chevron-down'});
        
            window.livewire.on('dragdrop',()=>{
                $('#tree1').treed();
            });
        })
    </script>
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header border-bottom d-md-flex justify-content-md-between align-items-md-center">
                    <div class="my-1 text-center text-md-start">
                        <label>
                            <input wire:model.debounce.500ms="search" type="search" class="form-control"
                                placeholder="Search..">
                        </label>
                    </div>
                    <div
                        class="text-md-end text-start d-flex align-items-center justify-content-end flex-md-row flex-column">
                        @if (!$selected)
                        <div class="my-1 me-md-2">
                            <label>
                                <select wire:model="paginate" class="form-select">
                                    <option value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select>
                            </label>
                        </div>
                        @can('create-menu')
                        <div class="flex-wrap my-1">
                            <a href="{{ route('menu.create') }}"
                                class="btn btn-secondary text-white add-new btn-primary">
                                <span>
                                    <i class="ti ti-plus me-0 me-sm-1 ti-xs"></i>
                                    <span>
                                        {{ $title }}
                                    </span>
                                </span>
                            </a>
                        </div>
                        @endcan
                        @else
                        <div class="my-1 me-md-2">
                            <span class="px-1">
                                {{ count($selected) }} data terpilih
                            </span>
                        </div>
                        <div class="flex-wrap my-1">
                            <a href="#" class="btn btn-secondary add-new btn-label-primary" data-bs-toggle="modal"
                                data-bs-target="#modalSelectedStatus">
                                Update Status
                            </a>
                        </div>
                        @endif
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table border-top">
                        <thead>
                            <tr>
                                <th style="width: 2%"></th>
                                <th>Menu</th>
                                <th>Permission</th>
                                <th>Main Menu</th>
                                <th class="text-center">No. Urut</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($table as $key => $item)
                            @php
                            $updateRoute = route('menu.update', $item->id);
                            @endphp

                            <tr wire:key="main-{{ $item->id }}">
                                <td style="width: 2%">
                                    <i class="ti ti-{{ $item->icon }} ti-sm mx-2 fs-5"></i>
                                </td>

                                <td class="col-3">
                                    <div class="d-flex flex-column">
                                        <a href="#" class="text-body text-truncate">
                                            <span class="fw-semibold">
                                                {{ $item->name }}
                                            </span>
                                        </a>
                                        <small class="text-muted">/{{ $item->url }}</small>
                                    </div>
                                </td>

                                <td class="col-3">
                                    @if($item->permission_id)
                                    {{ $item->permission->name }}
                                    @endif
                                </td>

                                <td class="col-3">
                                    @if($item->main_menu)
                                    {{ $item->parent->name }}
                                    @endif
                                </td>

                                <td class="col-3 text-center">
                                    {{ $item->sort }}
                                </td>

                                <td>
                                    <div class="d-flex align-items-center">
                                        @can('update-menu')
                                        <a href="{{ route('menu.edit', $item->id) }}" class="action-btn" title="edit">
                                            <i class="ti ti-edit ti-sm me-2 fs-5"></i>
                                        </a>
                                        @endcan

                                        @can('delete-menu')
                                        <a href="javascript:;" class="action-btn" title="delete" data-bs-toggle="modal"
                                            data-bs-target="#modalDelete{{ $item->id }}">
                                            <i class="ti ti-trash ti-sm mx-2 fs-5"></i>
                                        </a>
                                        @include('admin.modal.delete')
                                        @endcan
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <div class="text-center col-md-7 mx-auto px-3 pt-3">
                                <div class="alert alert-secondary">
                                    Data tidak ditemukan
                                </div>
                            </div>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                <div class="card-body d-md-flex justify-content-md-between align-items-center pt-3 pb-2">
                    <div class="align-self-start my-2 d-none d-md-block text-muted">
                        <small>
                            Showing {{ $table->firstItem() }} to {{ $table->lastItem() }} of {{ $table->total() }} data
                        </small>
                    </div>
                    {{ $table->links() }}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title m-0 me-2">Urutan Menu</h5>
                    <a href="{{ route('menu.index') }}" class="btn btn-sm btn-label-primary" id="teamMemberList">
                        <i class="ti ti-refresh ti-xs me-1"></i>
                        Sync
                    </a>
                </div>
                <div class="card-body">
                    <div class="fw-semibold">
                        <div id="tree1">
                            <div wire:sortable="updateParentOrder" wire:sortable-group="updateChildGroup">
                                @foreach (getMenu() as $menu)
                                <div class="ms-1 d-flex align-items-center text-body h6 mt-2"
                                    wire:key="menu-{{ $menu->id }}" wire:sortable.item="{{ $menu->id }}">
                                    <i class="ti ti-{{ $menu->icon }} text-body me-2"></i>
                                    {{ $menu->name }}
                                </div>

                                <ul wire:sortable-group.item-group="{{ $menu->id }}">
                                    @foreach ($menu->subMenu as $child)
                                    <li wire:key="child-{{ $child->id }}" wire:sortable-group.item="{{ $child->id }}">
                                        <div class="ms-1">
                                            {{ $child->name }}
                                        </div>
                                    </li>
                                    @endforeach
                                </ul>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/admin/stat.blade.php
<div class="card">
    <div class="card-header">
        <h5 class="card-title mb-3">Rekap Transaksi</h5>
        <div class="row ">
            <div class="col-md-3">
                <select wire:model="category_id" id="UserPlan" class="form-select text-capitalize">
                    <option value="">Semua Jenis Barang</option>
                    @foreach ($categories as $key => $category)
                    <option value="{{ $key }}">{{ $category }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-3">
                <input wire:model="start_date" class="form-control" type="date">
            </div>
            <div class="col-md-3">
                <input wire:model="end_date" class="form-control" type="date">
            </div>

        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table border-top">
                <thead>
                    <tr>
                        <th>Nama Barang</th>
                        <th>Jenis Barang</th>
                        <th class="text-center">Terjual</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transactions as $key => $item)
                    <tr wire:key="row{{ $key }}">
                        <td>{{ $item->product->name }}</td>
                        <td>{{ $item->product->category->name }}</td>
                        <td class="text-center">{{ $item->total_qty }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>