routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserAdminController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::prefix('admin')->middleware(['auth', 'auth.status'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserAdminController::class);
    Route::put('/user/{id}/password', [UserAdminController::class, 'updatePassword'])->name('user.update.password');

    Route::resource('role', RoleController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('setting', SettingController::class);

    Route::resource('category', CategoryController::class);
    Route::resource('product', ProductController::class);

    Route::resource('transaction', TransactionController::class);

});

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Stock;
use App\Models\Category;
use App\Models\Transaction;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function scopeFilter($query, $search) 
    {
        $query->when($search ?? false, function($query, $search){
            return $query->where('name', 'like', "%$search%");
        });
    }

    /**
     * Get the category that owns the Product
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * Get the stock associated with the Product
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function stock()
    {
        return $this->hasOne(Stock::class, 'product_id');
    }

    /**
     * Get all of the transactions for the Product
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class, 'product_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Product as Model;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public $model, $view, $route;

    public function __construct(Model $model)
    {
        $this->model = $model;
        $this->view = 'admin.product';
        $this->route = 'product';

        $this->middleware('can:create-' . $this->route)->only('create','store');
        $this->middleware('can:read-' . $this->route)->only('index');
        $this->middleware('can:update-' . $this->route)->only('edit','update');
        $this->middleware('can:delete-' . $this->route)->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->view . '.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $categories = Category::pluck('name', 'id');
        return view($this->view . '.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'category_id' => 'required',
            'name' => 'required|unique:products,name',
            'description' => 'nullable',
            'quantity' => 'nullable',
        ]);

        DB::transaction(function () use($data) {
            $model = $this->model->create($data);
            $model->stock()->create([
                'quantity' => $data['quantity']
            ]);
        });

        alertNotif('save');
        return redirect()->route($this->route . '.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->findOrFail($id);
        $categories = Category::pluck('name', 'id');
        return view($this->view . '.edit', compact('data', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = $this->model->find($id);
        $data = $request->validate([
            'category_id' => 'required',
            'name' => 'required|unique:products,name,'.$id,
            'description' => 'nullable',
            'quantity' => 'nullable',
        ]);

        DB::transaction(function () use($model, $data) {
            $model->update($data);
            $model->stock()->update([
                'quantity' => $data['quantity']
            ]);
        });

        alertNotif('update');
        return redirect()->route($this->route . '.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);

        DB::transaction(function () use($model) {
            $model->stock()->delete();
            $model->delete();
        });

        alertNotif('delete');
        return redirect()->route($this->route . '.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Product')

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Create @yield('title')</h5>
                    <small class="text-muted">Buat @yield('title')</small>
                </div>
                <a href="{{ route('product.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('product.store') }}" method="POST">
                    @csrf

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row">
                        <div class="mb-3 col-md-5">
                            <label for="category_id" class="form-label">Jenis Barang</label>
                            <select class="form-select" name="category_id" id="category_id" autofocus required>
                                <option value="" selected disabled>Pilih</option>
                                @foreach ($categories as $key => $category)
                                <option value="{{ $key }}" @selected(old('category_id')==$key)>{{ $category }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="mb-3 col-md-7">
                            <label for="name" class="form-label">Nama</label>
                            <input class="form-control" type="text" id="name" name="name" value="{{ old('name') }}"
                                placeholder="Nama Barang" required />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="description" class="form-label">Deskripsi (Opsional)</label>
                            <textarea class="form-control" name="description" id="description" rows="3"
                                placeholder="Deskripsi Produk">{{ old('description') }}</textarea>
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="quantity" class="form-label">Stok</label>
                            <input class="form-control" type="number" min="0" id="quantity" name="quantity"
                                value="{{ old('quantity') }}" placeholder="Jumlah Stok" required />
                        </div>

                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Submit</button>
                        <a href="{{ route('product.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin.app')
@section('title', 'Product')

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Edit @yield('title')</h5>
                    <small class="text-muted">Perbarui @yield('title')</small>
                </div>
                <a href="{{ route('product.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('product.update', $data->id) }}" method="POST">
                    @csrf
                    @method('PUT')

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="category_id" class="form-label">Jenis Barang</label>
                            <select class="form-select" name="category_id" id="category_id" autofocus required>
                                <option value="" selected disabled>Pilih</option>
                                @foreach ($categories as $key => $category)
                                <option value="{{ $key }}" @selected($data->category_id == $key)>
                                    {{ $category }}
                                </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="mb-3 col-md-6">
                            <label for="name" class="form-label">Nama</label>
                            <input class="form-control" type="text" id="name" name="name" value="{{ $data->name }}"
                                placeholder="Nama Barang" required />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="description" class="form-label">Deskripsi (Opsional)</label>
                            <textarea class="form-control" name="description" id="description" rows="3"
                                placeholder="Deskripsi Produk">{{ $data->description }}</textarea>
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="quantity" class="form-label">Stok</label>
                            <input class="form-control" type="number" min="0" id="quantity" name="quantity"
                                value="{{ $data->stock->quantity }}" placeholder="Jumlah Stok" required />
                        </div>

                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Update</button>
                        <a href="{{ route('product.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Product')

@push('style')
<link rel="stylesheet" href="{{ asset('theme/assets/css/custom.css') }}" />
@endpush

@push('script')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<x-livewire-alert::scripts />
@endpush

@section('content')
@livewire('admin.show-product', ['title' => $__env->yieldContent('title')])
@endsection