routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserAdminController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::prefix('admin')->middleware(['auth', 'auth.status'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserAdminController::class);
    Route::put('/user/{id}/password', [UserAdminController::class, 'updatePassword'])->name('user.update.password');

    Route::resource('role', RoleController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('setting', SettingController::class);

    Route::resource('category', CategoryController::class);
    Route::resource('product', ProductController::class);

    Route::resource('transaction', TransactionController::class);

});

app/Http/Controllers/Admin/TransactionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\Transaction as Model;

class TransactionController extends Controller
{
    public $model, $view, $route;

    public function __construct(Model $model)
    {
        $this->model = $model;
        $this->view = 'admin.transaction';
        $this->route = 'transaction';

        $this->middleware('can:create-' . $this->route)->only('create','store');
        $this->middleware('can:read-' . $this->route)->only('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->view . '.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::whereHas('stock', function($query) {
                $query->where('quantity', '>', 0);
            })->select('id', 'name')->get();
        return view($this->view . '.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'date' => 'required',
            'product_id' => 'required',
            'quantity' => 'required',
        ]);

        $product = Product::find($data['product_id']);
        $data['initial_stock'] = $product->stock->quantity;
        $data['final_stock'] = $data['initial_stock'] - $data['quantity'];
        
        DB::transaction(function () use($data, $product) {
            $this->model->create($data);
            $product->stock()->update([
                'quantity' => $data['final_stock']
            ]);
        });
        
        alertNotif('save');
        return redirect()->route($this->route . '.index');
    }

}

resources/views/admin/transaction/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Transaction')

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Create @yield('title')</h5>
                    <small class="text-muted">Buat @yield('title')</small>
                </div>
                <a href="{{ route('transaction.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('transaction.store') }}" method="POST">
                    @csrf

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row">
                        <div class="mb-3 col-md-5">
                            <label for="date" class="form-label">Tanggal</label>
                            <input class="form-control" type="date" name="date" id="date" placeholder="Jumlah Terjual"
                                value="{{ old('date') }}" autofocus required>
                        </div>

                        <div class="mb-3 col-md-7">
                            <label for="product_id" class="form-label">Barang</label>
                            <select class="form-select" name="product_id" id="product_id" required>
                                <option value="" disabled selected>Pilih</option>
                                @foreach ($products as $product)
                                <option value="{{ $product->id }}" @selected(old('product_id')==$product->id)>
                                    {{ $product->name }}
                                </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="quantity" class="form-label">Jumlah</label>
                            <input class="form-control" type="number" min="1" name="quantity" id="quantity"
                                placeholder="Jumlah Terjual" value="{{ old('quantity') }}" required>
                        </div>


                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Submit</button>
                        <a href="{{ route('transaction.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transaction/edit.blade.php
@extends('layouts.admin.app')
@section('title', 'Transaction')

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Edit @yield('title')</h5>
                    <small class="text-muted">Perbarui @yield('title')</small>
                </div>
                <a href="{{ route('transaction.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('transaction.update', $data->id) }}" method="POST">
                    @csrf
                    @method('PUT')

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row">
                        <div class="mb-3 col-md-12">
                            <label for="name" class="form-label">Nama</label>
                            <input class="form-control" type="text" id="name" name="name" value="{{ $data->name }}"
                                placeholder="Nama" autofocus required />
                        </div>
                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Update</button>
                        <a href="{{ route('transaction.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transaction/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Transaction')

@push('style')
<link rel="stylesheet" href="{{ asset('theme/assets/css/custom.css') }}" />
@endpush

@push('script')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<x-livewire-alert::scripts />
@endpush

@section('content')
@livewire('admin.show-transaction', ['title' => $__env->yieldContent('title')])
@endsection