routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserAdminController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::prefix('admin')->middleware(['auth', 'auth.status'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('user', UserAdminController::class);
    Route::put('/user/{id}/password', [UserAdminController::class, 'updatePassword'])->name('user.update.password');

    Route::resource('role', RoleController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('menu', MenuController::class);
    Route::resource('setting', SettingController::class);

    Route::resource('category', CategoryController::class);
    Route::resource('product', ProductController::class);

    Route::resource('transaction', TransactionController::class);

});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Setting as Model;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class SettingController extends Controller
{
    public $model, $view, $route;

    public function __construct(Model $model)
    {
        $this->model = $model;
        $this->view = 'admin.setting';
        $this->route = 'setting';

        $this->middleware('can:create-' . $this->route)->only('create','store');
        $this->middleware('can:read-' . $this->route)->only('index');
        $this->middleware('can:update-' . $this->route)->only('edit','update');
        $this->middleware('can:delete-' . $this->route)->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->view . '.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->view . '.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'app_name' => 'required',
            'app_version' => '',
            'name' => 'required',
            'address' => '',
            'logo' => 'image|max:800|nullable'
        ]);

        $data['logo'] = storeImage($request, 'logo', 'setting');
        $this->model->create($data);
        alertNotif('save');

        return redirect()->route($this->route . '.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->findOrFail($id);
        return view($this->view . '.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = $this->model->find($id);
        $data = $request->validate([
            'app_name' => 'required',
            'app_version' => '',
            'name' => 'required',
            'address' => '',
            'logo' => 'image|mimes:png,jpg,jpeg|max:800|nullable'
        ]);

        $data['logo'] = updateImage($request, 'logo', 'setting', $model->logo);
        $data['updated_by'] = auth()->user()->id;
        $model->update($data);
        alertNotif('update');

        return redirect()->route($this->route . '.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = $this->model->find($id);

        if ($model->logo) {
            Storage::delete($model->logo);
        }

        $model->delete();
        alertNotif('delete');

        return redirect()->route($this->route . '.index');
    }
}

resources/views/admin/setting/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Setting')

@push('script')
<script>
    $(function () {
        // upload image
        let accountUserImage = document.getElementById('uploadedAvatar');
        const fileInput = document.querySelector('.account-file-input'),
        resetFileInput = document.querySelector('.account-image-reset');

        if (accountUserImage) {
        const resetImage = accountUserImage.src;
        fileInput.onchange = () => {
            if (fileInput.files[0]) {
            accountUserImage.src = window.URL.createObjectURL(fileInput.files[0]);
            }
        };
        resetFileInput.onclick = () => {
            fileInput.value = '';
            accountUserImage.src = resetImage;
        };
        }
    });
</script>
@endpush

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Create @yield('title')</h5>
                    <small class="text-muted">Buat @yield('title')</small>
                </div>
                <a href="{{ route('setting.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('setting.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row mt-3">
                        <div class="d-flex align-items-start align-items-sm-center gap-4">
                            <img src="{{ asset('Thumbnail.jpg') }}" alt="logo" class="d-block w-px-100 h-px-100 rounded"
                                id="uploadedAvatar">
                            <div class="button-wrapper">
                                <label for="upload" class="btn btn-primary me-2 mb-3 waves-effect waves-light"
                                    tabindex="0">
                                    <span class="d-none d-sm-block">Upload Logo</span>
                                    <i class="ti ti-upload d-block d-sm-none"></i>
                                    <input name="logo" type="file" id="upload" class="account-file-input"
                                        accept="image/png, image/jpeg" hidden="">
                                </label>
                                <button type="button"
                                    class="btn btn-label-secondary account-image-reset mb-3 waves-effect">
                                    <i class="ti ti-refresh-dot d-block d-sm-none"></i>
                                    <span class="d-none d-sm-block">Reset</span>
                                </button>

                                <div class="text-muted">Allowed JPG, GIF or PNG. Max size of 800K</div>
                            </div>
                        </div>
                    </div>

                    <hr class="my-4">

                    <div class="row">
                        <div class="mb-3 col-md-8">
                            <label for="name" class="form-label">Nama</label>
                            <input class="form-control" type="text" id="name" name="app_name"
                                value="{{ old('app_name') }}" placeholder="Nama App" autofocus required />
                        </div>

                        <div class="mb-3 col-md-4">
                            <label for="version" class="form-label">Versi</label>
                            <input class="form-control" type="text" id="version" name="app_version"
                                value="{{ old('app_version') }}" placeholder="v1.0" />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="name" class="form-label">Nama Insitusi</label>
                            <input class="form-control" type="text" id="name" name="name" value="{{ old('name') }}"
                                placeholder="Nama Insitusi" required />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="address" class="form-label">Alamat Insitusi</label>
                            <textarea class="form-control" name="address" id="address" rows="4"
                                placeholder="Alamat Insitusi"></textarea>
                        </div>
                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Submit</button>
                        <a href="{{ route('setting.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('layouts.admin.app')
@section('title', 'Setting')

@push('script')
<script>
    $(function () {
        // upload image
        let accountUserImage = document.getElementById('uploadedAvatar');
        const fileInput = document.querySelector('.account-file-input'),
        resetFileInput = document.querySelector('.account-image-reset');

        if (accountUserImage) {
        const resetImage = accountUserImage.src;
        fileInput.onchange = () => {
            if (fileInput.files[0]) {
            accountUserImage.src = window.URL.createObjectURL(fileInput.files[0]);
            }
        };
        resetFileInput.onclick = () => {
            fileInput.value = '';
            accountUserImage.src = resetImage;
        };
        }
    });
</script>
@endpush

@section('content')
<div class="row">
    <div class="col-md-9 mx-md-auto">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <div class="card-title mb-0">
                    <h5 class="mb-0">Edit @yield('title')</h5>
                    <small class="text-muted">Perbarui @yield('title')</small>
                </div>
                <a href="{{ route('setting.index') }}" class="btn p-0" title="Kembali">
                    <i class="ti ti-x ti-sm text-muted"></i>
                </a>
            </div>

            <div class="card-body">
                <form action="{{ route('setting.update', $data->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Terdapat beberapa masalah dengan inputan Anda.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="row mt-3">
                        <div class="d-flex align-items-start align-items-sm-center gap-4">
                            <img src="@if(!$data->logo) http://shofyan.my.id/theme/images/portfolio/psb.jpg @else {{ imageAsset($data->logo) }} @endif"
                                alt="logo" class="d-block w-px-100 h-px-100 rounded" id="uploadedAvatar">
                            <div class="button-wrapper">
                                <label for="upload" class="btn btn-primary me-2 mb-3 waves-effect waves-light"
                                    tabindex="0">
                                    <span class="d-none d-sm-block">Change Logo</span>
                                    <i class="ti ti-upload d-block d-sm-none"></i>
                                    <input name="logo" type="file" id="upload" class="account-file-input"
                                        accept="image/png,image/jpeg" hidden="">
                                </label>
                                <button type="button"
                                    class="btn btn-label-secondary account-image-reset mb-3 waves-effect">
                                    <i class="ti ti-refresh-dot d-block d-sm-none"></i>
                                    <span class="d-none d-sm-block">Reset</span>
                                </button>

                                <div class="text-muted">Allowed JPG, GIF or PNG. Max size of 800K</div>
                            </div>
                        </div>
                    </div>

                    <hr class="my-4">

                    <div class="row">
                        <div class="mb-3 col-md-8">
                            <label for="name" class="form-label">Nama</label>
                            <input class="form-control" type="text" id="name" name="app_name"
                                value="{{ $data->app_name }}" placeholder="Nama App" autofocus required />
                        </div>

                        <div class="mb-3 col-md-4">
                            <label for="version" class="form-label">Versi</label>
                            <input class="form-control" type="text" id="version" name="app_version"
                                value="{{ $data->app_version }}" placeholder="v1.0" />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="name" class="form-label">Nama Insititusi</label>
                            <input class="form-control" type="text" id="name" name="name" value="{{ $data->name }}"
                                placeholder="Nama Insititusi" required />
                        </div>

                        <div class="mb-3 col-md-12">
                            <label for="address" class="form-label">Alamat Insititusi</label>
                            <textarea class="form-control" name="address" id="address" rows="4"
                                placeholder="Alamat Insititusi">{{ $data->address }}</textarea>
                        </div>
                    </div>

                    <div class="my-2">
                        <button type="submit" class="btn btn-primary px-5 me-2">Update</button>
                        <a href="{{ route('setting.index') }}" class="btn btn-label-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setting/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Setting')

@push('style')
<link rel="stylesheet" href="{{ asset('theme/assets/css/custom.css') }}" />
@endpush

@push('script')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<x-livewire-alert::scripts />
@endpush

@section('content')
@livewire('admin.show-setting', ['title' => $__env->yieldContent('title')])
@endsection